# Dette er Jespers fil

# import turtle

def vuffer(): # hvad tror du denne her tegner ? :-)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(20)
